In [49]:
import cv2
import numpy as np
from numpy import shape
import matplotlib.pyplot as plt 
from image_extractor import feature_extract

image_dir  = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Agglutinated/image (1).JPG'
# image_dir  = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Brittle/image (1).JPG'
# image_dir = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Plated_Purple/image (10).JPG'
# image_dir = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Compartmentalized_PartiallyPurple/image (1).JPG'
# image_dir = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Compartmentalized_Brown/image (1).JPG'
# image_dir = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Plated_White/image (72).JPG'
# image_dir = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Plated_Slaty/image (71).JPG'
# image_dir = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Compartmentalized_Slaty/image (1).JPG'
# image_dir = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Moldered/image (7).JPG'
# image_dir = 'D:/Thesis_data/mlp_data/testing_img/Agglutinated/image(1).JPG'

plt.rcParams['figure.dpi'] = 102.46 

In [50]:
extractor = feature_extract()
image_bgr = cv2.imread(image_dir)
extractor.extract(image_bgr)


In [51]:
((extractor.structure))

array([ 1.16905847e+02,  1.92123878e+02,  2.13175139e+01,  1.82028539e+01,
        1.07164994e+02,  8.88384659e+01,  4.86391635e+00,  2.03321905e+01,
        1.53500000e+02,  3.58500000e+02,  3.00000000e+00,  7.00000000e+00,
        1.20477545e+02,  2.30354332e+02,  2.22703800e+01,  4.05445004e+00,
        4.15882378e+01,  1.34852936e+02,  3.41282196e+01,  4.28746462e+00,
        1.48819399e+02,  1.73754753e+02,  1.87194552e+01,  3.95500070e+00,
        6.50201741e+01,  8.09658881e+01,  1.94686114e+01,  2.32116513e+01,
        3.59255986e+01,  4.00263892e+01,  1.06907737e+00,  3.45662437e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        6.00544682e+01,  8.99697037e+01,  1.10917606e+01,  3.28243256e-01,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        5.99914552e+01,  5.07410583e+01,  8.32715311e+00,  8.48550720e-01,
       -1.28846792e-02, -1.30859403e-01,  8.87244506e-01,  2.45538048e+00,
       -1.48473208e+00,  

In [52]:
print(extractor.n2)

38


In [53]:
shape(extractor.mold)

(56,)

In [54]:
print(extractor.overall_geometry)

[252, 373, 77269.0, 1172.4894560575485, 267.4194030761719, 383.3051452636719, 1.6402595137482228, 79956.5, 196.33718872070312, 0.9663879734605691, 0.822045618962509, 6.103277807866851]


In [55]:
(extractor.overall_rgb_stat)

array([90.08984   , 79.8994    , 52.618237  , 49.549633  , 45.39174   ,
       30.185934  , -0.8192901 , -0.68765134, -0.46233264, -0.61187583,
       -0.75621855, -0.45938212], dtype=float32)

In [56]:
extractor.overall_hsv_stat

array([23.079918  , 85.97742   , 90.780014  , 29.30934   , 48.817097  ,
       49.629498  ,  3.9593065 , -0.5897722 , -0.84107566, 17.02361   ,
       -0.595323  , -0.57765955], dtype=float32)

In [57]:
shape(extractor.glcm_correlation)

(12,)

In [58]:
shape(extractor.glcm_dissimilarity)

(12,)

In [59]:
shape(extractor.grid_stat)

(192,)