In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt 
from image_extractor import select_feature

image_dir  = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Agglutinated/image (99).JPG'
# image_dir = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Plated_Purple/image (2).JPG'
# image_dir = 'D:/Thesis_data/Backups/Color_Corrected_512x512/Compartmentalized_Purple/image (69).JPG'


plt.rcParams['figure.dpi'] = 102.46
plt.rcParams["figure.figsize"] = (12,6)

image  = cv2.imread(image_dir)


In [3]:
ov_geo, ov_stat, geo_ft, stat_ft, glcm_con, glcm_dis, glcm_ene, glcm_cor = select_feature(image)


In [6]:
# print(np.shape(glcm))
print(glcm_con)
print(glcm_dis)
print(glcm_ene)
print(glcm_cor)

[[1.45789247 1.5361124  0.70159314 1.53987957]
 [2.89378125 2.37585927 1.60585474 2.43460192]
 [3.8404154  3.51232079 2.24598481 3.72532642]
 [4.52079029 3.96760924 2.84375    4.20879085]]
[[0.62355438 0.64489733 0.40790441 0.65218465]
 [0.96378125 0.85473691 0.68342391 0.86898513]
 [1.17216082 1.11299923 0.84247385 1.15133769]
 [1.31411415 1.21147929 0.97458584 1.25041298]]
[[0.45509411 0.45125846 0.4726026  0.45102935]
 [0.42521882 0.43063276 0.44689147 0.43087172]
 [0.40536494 0.40255713 0.43065034 0.40320024]
 [0.3892907  0.39116334 0.41830593 0.39255869]]
[[0.87417658 0.86755543 0.93938258 0.86723062]
 [0.75002697 0.79548231 0.86151784 0.79042565]
 [0.66643223 0.69689851 0.80671002 0.67851684]
 [0.60481767 0.65692054 0.75579837 0.63606554]]
